### ISSUE TITLE
Revoking a role

### ISSUE THREAD

**Issue by boedy** [myclabs/ACL#19]
All tests in this repo grant a role and then revoke the same role. This works fine, because the role is already in memory I think. How do I lookup the role for a use which is associated with some resource x.

Right now I'm getting:

`Entity has to be managed or scheduled for removal for single computation`

for

``` php
$this->acl->revoke($user, new LocationManager($user, $location));
```

**Comment by mnapoli** [comment]
Since the role is a Doctrine entity, you need to get it from the database. You can get it through the entity manager by its ID. For example if you list all the roles of a user in a table, each row can have a "delete" button.

You can also get the role from `User::getRoles()` (see http://myclabs.github.io/ACL/doc/usage.html the user has a list of roles).

Does that answer your question?

FYI in #9 a refactoring was planned where roles would be "static" (not stored in database). That was never finished unfortunately, but maybe it will interest you.

**Comment by boedy** [comment]
Thanks for responding so quickly :+1: 

Thats what I thought: "I'll just loop the user roles an revoke the one which is associated with resource x"  something like this:

``` php
foreach ($user->getRoles() as $role) {
    if($role instanceof LocationManager){
        ($role->getResource()->getId() == $locationId){
            $this->acl->revoke($user, $role);
        }
    }
}
```

Is this possible?

 I just look at the PR you are referencing. I think this method would be used for that:

`findByRoleAndResource`

**Comment by mnapoli** [comment]
Yes. You could also have a look at the role repository: https://github.com/myclabs/ACL/blob/master/src/Repository/RoleRepository.php#L17 (you can use the existing method, or use DQL to create a custom query for example).
